# Generated by Django 2.2.12 on 2021-03-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210305_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsTest',
        ),
    ]
